a = input('Digite algo: ')
print('Qual é o tipo?', type(a))
print('Tem espaços?', a.isspace())
print('Tem números?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É Alfanumérico?', a.isalnum())
print('É maiúsculo?', a.isupper())
print('É minúsculo?', a.islower())
print('É capitalizado?', a.istitle())
